TrajectoryPlannerROS:
#  recovery_behaviour_enabled: true
# Robot Configuration Parameters
  max_vel_x: 0.15
  min_vel_x: -0.08

  max_vel_theta:  1.0
  min_vel_theta: -1.0
  min_in_place_vel_theta: 1.0

  acc_lim_x: 1.0
  acc_lim_y: 0.0
  acc_lim_theta: 0.6

# Goal Tolerance Parameters
  xy_goal_tolerance: 0.10
  yaw_goal_tolerance: 0.05

# Differential-drive robot configuration
  holonomic_robot: false

# Forward Simulation Parameters
  sim_time: 0.8
  vx_samples: 18
  vtheta_samples: 20
  sim_granularity: 0.05

  pdist_scale: 0.6
  gdist_scale: 0.8
  occdist_scale: 0.2 #
#  dwa: false
  meter_scoring: true
